# Single source of truth: (group, name, role, current, refine, fresh, status)
# status: keep = existing token, same name · new = added token · fix = existing name that was undefined/broken
T = [
 # ---------- colour
 ("Colour","--clr-base","Primary action: buttons, CTA bar, active states","#018E87","#007A74","#3E4C8A","keep"),
 ("Colour","--clr-base-strong","Hover / pressed, CTA bar ground","#018E87","#0B5E59","#2F3A6E","new"),
 ("Colour","--clr-brand","Logo teal — decorative & large text only","#018E87","#018E87","#3E4C8A","new"),
 ("Colour","--clr-accent","Soft highlight on dark grounds","#66CCC7","#7FD1CB","#C9BDF0","new"),
 ("Colour","--clr-text","Headings, strong text","#000000","#1B2B2A","#1E2530","keep"),
 ("Colour","--clr-text-2","Running text","#333333","#3A4948","#4A5568","new"),
 ("Colour","--clr-text-muted","Captions, meta","#333333","#5C6B6A","#5E6676","new"),
 ("Colour","--clr-text-inverse","Text on dark / brand grounds","#FFFFFF","#FFFFFF","#FFFFFF","keep"),
 ("Colour","--clr-bg","Page ground (kept as alias of surface)","#EEEEEE","#F2F5F4","#F3F4F8","keep"),
 ("Colour","--clr-surface","Page ground","#EEEEEE","#F2F5F4","#F3F4F8","new"),
 ("Colour","--clr-surface-raised","Cards, chips, buttons on photo","#FFFFFF","#FFFFFF","#FFFFFF","new"),
 ("Colour","--clr-border","Hairlines on cards and chips","transparent","#D9E2E1","#DDE0EA","new"),
 ("Colour","--clr-tint","Knowledge-base band","#66CCC7","#E6F2F1","#EEEBFA","new"),
 ("Colour","--clr-on-tint","Heading on the tint band","#FFFFFF","#0B5E59","#2F3A6E","new"),
 ("Colour","--clr-dark","Footer ground (alias)","#444444","#12302E","#1E2530","keep"),
 ("Colour","--clr-footer-bg","Footer ground","#444444","#12302E","#1E2530","new"),
 ("Colour","--clr-footer-link","Footer links","#FFFFFF","#A9DCD8","#C9BDF0","new"),
 ("Colour","--clr-focus","Keyboard focus ring","#FFFFFF","#018E87","#5B4BA8","new"),
 ("Colour","--clr-overlay","Nav overlay","#00000080","#12302EB3","#1E2530B3","keep"),
 ("Colour","--hero-scrim","Hero photo overlay","rgb(0 0 0 / .5) + blur(5px)","linear-gradient(180deg, rgb(18 48 46 / .15) 0%, rgb(18 48 46 / .35) 45%, rgb(18 48 46 / .85) 100%)","linear-gradient(180deg, rgb(30 37 48 / .10) 0%, rgb(47 58 110 / .35) 45%, rgb(30 37 48 / .88) 100%)","new"),
 # ---------- type
 ("Type","--font-regular","Body & UI family","Raleway, sans-serif","Raleway, system-ui, sans-serif","Onest, system-ui, sans-serif","keep"),
 ("Type","--font-display","Headings family","Raleway, sans-serif","Raleway, system-ui, sans-serif","Fraunces, Georgia, serif","new"),
 ("Type","--font-text","Paragraphs & prose lists (defaults to the body/UI family)","Raleway, sans-serif","var(--font-regular)","var(--font-regular)","new"),
 ("Type","--text-size-adjust","x-height normalisation for --font-text","none","none","none","new"),
 ("Type","--display-variation","Variable-font axes for headings","normal","normal","\"SOFT\" 100, \"WONK\" 0","new"),
 ("Type","--numerals","Figure style (phone numbers, addresses)","normal (old-style in Raleway)","lining-nums","lining-nums","new"),
 ("Type","--font-weight-body","Running text","400 (300 on body)","400","400","new"),
 ("Type","--font-weight-h1","Page title","500","600","500","new"),
 ("Type","--font-weight-h2","Section title","400 (700 on tint band)","500","400","new"),
 ("Type","--font-weight-card","Service card title","700","600","500","new"),
 ("Type","--font-weight-ui","Buttons, CTA, nav","700","600","600","new"),
 ("Type","--font-size-small","Captions","0.75rem","0.875rem","0.875rem","keep"),
 ("Type","--font-size-paragraph","Body","clamp(1rem, .9512rem + .2439vi, 1.125rem)","clamp(1rem, .95rem + .25vi, 1.125rem)","clamp(1rem, .95rem + .25vi, 1.125rem)","keep"),
 ("Type","--font-size-h5","Card titles, footer heading","clamp(1.25rem, 1.189rem + .3049vi, 1.4063rem)","clamp(1.125rem, 1.08rem + .2vi, 1.25rem)","clamp(1.125rem, 1.08rem + .2vi, 1.25rem)","keep"),
 ("Type","--font-size-h4","Sub-headings","clamp(1.5625rem, 1.4863rem + .3811vi, 1.7578rem)","clamp(1.25rem, 1.17rem + .35vi, 1.5rem)","clamp(1.25rem, 1.17rem + .35vi, 1.5rem)","keep"),
 ("Type","--font-size-h3","Sub-sections","clamp(1.9531rem, 1.8579rem + .4764vi, 2.1973rem)","clamp(1.5rem, 1.38rem + .5vi, 1.875rem)","clamp(1.5rem, 1.38rem + .5vi, 1.875rem)","keep"),
 ("Type","--font-size-h2","Section titles","clamp(2.4414rem, 2.3223rem + .5955vi, 2.7466rem)","clamp(1.875rem, 1.65rem + 1vi, 2.5rem)","clamp(1.875rem, 1.6rem + 1.2vi, 2.625rem)","keep"),
 ("Type","--font-size-h1","Page title (incl. hero)","clamp(3.0518rem, …) — hero overrides to 2rem","clamp(2.25rem, 1.9rem + 1.6vi, 3.25rem)","clamp(2.375rem, 1.9rem + 2vi, 3.5rem)","keep"),
 ("Type","--font-size-h6","Nav chevron (used, never defined)","— undefined","1rem","1rem","fix"),
 ("Type","--line-height-body","Running text","var(--font-size-h4) ≈ 1.56","1.65","1.6","new"),
 ("Type","--line-height-heading","Headings","1.3","1.2","1.15","new"),
 ("Type","--tracking-heading","Heading letter-spacing","0","-0.01em","-0.015em","new"),
 ("Type","--measure","Max line length for prose","none (≈120 characters)","68ch","66ch","new"),
 # ---------- space
 ("Space","--space-quarter","4px","0.25rem","0.25rem","0.25rem","keep"),
 ("Space","--space-small","Used by .phone-link, never defined","— undefined","0.5rem","0.5rem","fix"),
 ("Space","--space-half","8px","0.5rem","0.5rem","0.5rem","keep"),
 ("Space","--space-normal","16px","1rem","1rem","1rem","keep"),
 ("Space","--space-double","32px","2rem","2rem","2rem","keep"),
 ("Space","--space-triple","Replaces stray 30px / 4rem / 6rem","— (30px, 4rem, 6rem hard-coded)","3rem","3rem","new"),
 ("Space","--space-section","Vertical rhythm between sections","—","clamp(3rem, 2rem + 4vi, 6rem)","clamp(3rem, 2rem + 4vi, 6rem)","new"),
 # ---------- shape
 ("Shape","--border-radius-small","Used by .phone-link, never defined","— undefined","0.5rem","0.5rem","fix"),
 ("Shape","--border-radius-circle","Declared as var(50%) — invalid","var(50%)","50%","50%","fix"),
 ("Shape","--radius-card","Service cards","0","1rem","1.25rem","new"),
 ("Shape","--radius-panel","Panels, article cards","2rem","1.5rem","1.75rem","new"),
 ("Shape","--radius-pill","Buttons, chips, CTA","2rem","999px","999px","new"),
 ("Shape","--shadow-1","Resting card","2rem 2rem 2rem #cacaca, -2rem -2rem 6rem #fff","0 1px 2px rgb(18 48 46 / .06), 0 4px 16px rgb(18 48 46 / .06)","0 1px 2px rgb(30 37 48 / .05), 0 6px 20px rgb(47 58 110 / .07)","new"),
 ("Shape","--shadow-2","Hovered card","same + scale(1.1)","0 2px 4px rgb(18 48 46 / .08), 0 14px 32px rgb(18 48 46 / .12)","0 2px 4px rgb(30 37 48 / .06), 0 16px 36px rgb(47 58 110 / .14)","new"),
 # ---------- motion & layout
 ("Motion","--duration-fast","Colour changes","0.15s","150ms","150ms","new"),
 ("Motion","--duration-base","Lift / move","0.3s","250ms","250ms","new"),
 ("Motion","--ease-out","Default easing","ease / ease-out","cubic-bezier(.2, .8, .2, 1)","cubic-bezier(.2, .8, .2, 1)","new"),
 ("Motion","--ease-in-out","Pass-through movements (card fill)","—","cubic-bezier(.65, 0, .35, 1)","cubic-bezier(.65, 0, .35, 1)","new"),
 ("Navigation","--nav-left","Drawer: left edge (auto = drawer on the right)","auto","auto","auto","new"),
 ("Navigation","--nav-right","Drawer: right edge","0","0","0","new"),
 ("Navigation","--nav-gap","Drawer: detachment from the viewport edges","0","0","0","new"),
 ("Navigation","--nav-width","Drawer: max width","23rem","23rem","23rem","new"),
 ("Navigation","--nav-pad","Drawer: inner side padding","0","0","0","new"),
 ("Navigation","--nav-radius","Drawer: corner radius","0","0","0","new"),
 ("Navigation","--nav-bg","Drawer: ground","#018E87","var(--clr-base)","var(--clr-base)","new"),
 ("Navigation","--nav-backdrop","Drawer: backdrop filter","none","none","none","new"),
 ("Navigation","--nav-border","Drawer: hairline","transparent","transparent","transparent","new"),
 ("Navigation","--nav-shadow","Drawer: shadow","none","none","none","new"),
 ("Navigation","--nav-hidden-x","Drawer: parked position when closed","100%","100%","100%","new"),
 ("Navigation","--nav-duration","Drawer: slide length","0.25s","250ms","250ms","new"),
 ("Navigation","--nav-z","Drawer stacking (C sits above the mobile bottom bar, z 800)","600","600","600","new"),
 ("Navigation","--nav-overlay-z","Dimmer stacking","500","500","500","new"),
 ("Navigation","--nav-overlay-bg","Page dimmer behind the open drawer","#00000080","#12302EB3","#1E2530B3","new"),
 ("Navigation","--nav-weight","Top-level items weight","700","700","700","new"),
 ("Navigation","--nav-tracking","Top-level items letter-spacing","0","0","0","new"),
 ("Navigation","--nav-size","Top-level items size","1rem","1rem","1rem","new"),
 ("Navigation","--nav-sub-case","Sub-items case","uppercase","uppercase","uppercase","new"),
 ("Navigation","--nav-sub-weight","Sub-items weight","700","700","700","new"),
 ("Navigation","--nav-close-size","Drawer close button box","—","2.25rem","2.25rem","new"),
 ("Navigation","--nav-close-inset","Close button inset from the drawer's right edge (centres it on the arrows)","—",".75rem",".75rem","new"),
 ("Navigation","--nav-close-top","Close button row top padding","1rem","1rem","1rem","new"),
 ("Navigation","--mnav-gap","Mobile bottom bar: detachment from the viewport edges","0","0","0","new"),
 ("Navigation","--mnav-radius","Mobile bottom bar: corner radius","0","0","0","new"),
 ("Navigation","--mnav-bg","Mobile bottom bar: ground","hsl(from #000 h s 30% / 80%)","hsl(from var(--clr-base-strong) h s l / 92%)","hsl(from var(--clr-base-strong) h s l / 92%)","new"),
 ("Navigation","--mnav-backdrop","Mobile bottom bar: backdrop filter","blur(5px)","blur(5px)","blur(5px)","new"),
 ("Navigation","--mnav-border","Mobile bottom bar: hairline","transparent","transparent","transparent","new"),
 ("Navigation","--mnav-shadow","Mobile bottom bar: shadow","0 0 10px rgb(0 0 0 / .2)","0 0 10px rgb(0 0 0 / .2)","0 0 10px rgb(0 0 0 / .2)","new"),
 ("Navigation","--mnav-pad-block","Mobile bottom bar: block padding","0.5rem 1rem","0.5rem 1rem","0.5rem 1rem","new"),
 ("Navigation","--mnav-pad-inline","Mobile bottom bar: inline padding","0.5rem","0.5rem","0.5rem","new"),
 ("Navigation","--nav-item-radius","Item hover/active shape","0","0","0","new"),
 ("Navigation","--nav-avatar-display","Specialist avatars in the Zespół sub-menu","none","none","none","new"),
 ("Navigation","--nav-avatar-size","Avatar diameter","—","2rem","2rem","new"),
 ("Navigation","--nav-avatar-pad","Space between the avatar and its row's hover edge","—","0","0","new"),
 ("Navigation","--nav-avatar-row-radius","Member row hover shape","—","var(--nav-item-radius)","var(--nav-item-radius)","new"),
 ("Navigation","--nav-avatar-fallback","Avatar placeholder (no photo)","—","rgb(255 255 255 / .12)","rgb(255 255 255 / .12)","new"),
 ("Navigation","--nav-avatar-ring","Avatar ring","—","rgb(255 255 255 / .16)","rgb(255 255 255 / .16)","new"),
 ("Navigation","--nav-avatar-ring-hover","Avatar ring on hover / focus","—","var(--clr-accent-soft)","var(--clr-accent-soft)","new"),
 ("Navigation","--nav-item-hover","Item hover ground","transparent","transparent","transparent","new"),
 ("Page header","--color-bg1","Sub-page header ground, start (page-header.css)","#3FA299","#3FA299","#3FA299","keep"),
 ("Page header","--color-bg2","Sub-page header ground, end","#3F8378","#3F8378","#3F8378","keep"),
 ("Page header","--color1","Aurora blob 1 (r, g, b)","18, 113, 255","18, 113, 255","18, 113, 255","keep"),
 ("Page header","--color2","Aurora blob 2","221, 74, 255","221, 74, 255","221, 74, 255","keep"),
 ("Page header","--color3","Aurora blob 3","100, 220, 255","100, 220, 255","100, 220, 255","keep"),
 ("Page header","--color4","Aurora blob 4","200, 50, 50","200, 50, 50","200, 50, 50","keep"),
 ("Page header","--color5","Aurora blob 5","180, 180, 50","180, 180, 50","180, 180, 50","keep"),
 ("Page header","--blending","Blob blend mode","hard-light","hard-light","hard-light","keep"),
 ("Page header","--ph-height","Header band height","40vh","40vh","40vh","new"),
 ("Page header","--ph-title-offset","Header title nudge down (clears the fixed top bar)","0","0","0","new"),
 ("Page header","--ph-title-size","Header title size (C: eyebrow)","var(--font-size-h2)","var(--font-size-h2)","var(--font-size-h2)","new"),
 ("Page header","--ph-title-tracking","Header title letter-spacing","0","0","0","new"),
 ("Page header","--ph-title-weight","Header title weight","500","500","500","new"),
 ("Layout","--index-bcrumb","Sticky breadcrumb layer: above page content, below the top bar (400)","5","390","390","new"),
 ("Layout","--content-width","Content column","80rem (panels: 1310px)","80rem","80rem","keep"),
 ("Layout","--bp-small","Phone breakpoint (reference; media queries can't read vars)","37.5rem","37.5rem","37.5rem","new"),
]

# Actual CSS values for "current" preview (where the table shows prose)
CURRENT_CSS = {
 "--hero-scrim":"rgb(0 0 0 / .5)",
 "--numerals":"normal",
 "--font-weight-body":"400","--font-weight-h2":"400",
 "--font-size-h1":"clamp(3.0518rem, 2.9029rem + .7443vi, 3.4332rem)",
 "--font-size-h6":"1rem","--space-small":".5rem","--border-radius-small":".5rem",
 "--border-radius-circle":"50%",
 "--line-height-body":"1.56","--measure":"none","--space-triple":"30px","--space-section":"2rem",
 "--shadow-2":"2rem 2rem 2rem #cacaca, -2rem -2rem 6rem #fff",
 "--ease-out":"ease","--content-width":"80rem","--bp-small":"37.5rem",
 "--tracking-heading":"0",
}

# ---------- rows added for direction C (values for current / refine / fresh keep their earlier look)
T += [
 ("Colour","--clr-accent-soft","Accent on dark grounds (footer links, hover)","—","#7FD1CB","#C9BDF0","new"),
 ("Colour","--clr-accent-strong","Accent used as text on light grounds","—","#0B5E59","#2F3A6E","new"),
 ("Colour","--clr-focus-on-dark","Focus ring on the photo and CTA bar","#FFFFFF","#FFFFFF","#FFFFFF","new"),
 ("Component","--btn-emph-bg","Hero booking button (Booksy) — ground","#FFFFFF","var(--clr-surface-raised)","var(--clr-surface-raised)","new"),
 ("Component","--btn-emph-fg","Hero booking button — label","#018E87","var(--clr-base)","var(--clr-base)","new"),
 ("Component","--btn-emph-hover-bg","Hero booking button — hover ground","#018E87","var(--clr-base-strong)","var(--clr-base-strong)","new"),
 ("Component","--btn-emph-hover-fg","Hero booking button — hover label","#FFFFFF","var(--clr-text-inverse)","var(--clr-text-inverse)","new"),
 ("Component","--cta-emph-bg","'Umów się na wizytę' in CTA bar — ground","transparent","transparent","transparent","new"),
 ("Component","--cta-emph-fg","'Umów się na wizytę' — label","#FFFFFF","var(--clr-text-inverse)","var(--clr-text-inverse)","new"),
 ("Component","--cta-emph-border","'Umów się na wizytę' — outline","currentColor","currentColor","currentColor","new"),
 ("Component","--cta-emph-fill","'Umów się na wizytę' — hover fill colour","—","transparent","transparent","new"),
 ("Component","--cta-emph-hover-bg","'Umów się na wizytę' — hover ground","rgb(255 255 255 / .15)","var(--clr-surface-raised)","var(--clr-surface-raised)","new"),
 ("Component","--cta-hover-bg","CTA bar links — hover ground (C: transparent, the fill colours it)","rgb(255 255 255 / .15)","var(--clr-surface-raised)","var(--clr-surface-raised)","new"),
 ("Component","--card-hover-border","Service card outline on hover","—","var(--clr-base)","var(--clr-base)","new"),
 ("Component","--card-hover-bg","Service card ground on hover","#018E87","var(--clr-surface-raised)","var(--clr-surface-raised)","new"),
 ("Component","--card-hover-fg","Service card title on hover","#FFFFFF","var(--clr-base-strong)","var(--clr-base-strong)","new"),
 ("Component","--card-hover-scale","Service card pop-out on hover","1.1","none","none","new"),
 ("Component","--card-hover-transform","Service card lift on hover","none","translateY(-4px)","translateY(-4px)","new"),
 ("Component","--panel-rail-gap","Gap between the heading rail and the text in text-only panels","—","clamp(2rem, 4vw, 4rem)","clamp(2rem, 4vw, 4rem)","new"),
 ("Component","--faq-pad-block","FAQ item block padding","—","1.125rem","1.125rem","new"),
 ("Component","--faq-pad-inline","FAQ item side padding","—","1.25rem","1.25rem","new"),
 ("Component","--action-panel-bg","Service page 'Zarejestruj w Booksy' panel ground","#018E87","var(--clr-base)","var(--clr-base)","new"),
 ("Component","--action-panel-fg","Service page booking panel label","#FFFFFF","var(--clr-text-inverse)","var(--clr-text-inverse)","new"),
 ("Component","--card-fill-mask","Hover fill shape (none = solid rise; diagonal stripe for sweep)","—","none","none","new"),
 ("Component","--card-fill-final","Colour the fill settles on","—","transparent","transparent","new"),
 ("Component","--card-fill-dx","Direction: 0 = rise (bottom → top), 1 = sweep (bottom-right → top-left)","—","0","0","new"),
 ("Component","--card-fill-w","Fill plane width","—","100%","100%","new"),
 ("Component","--card-fill-h","Fill plane height","—","100%","100%","new"),
 ("Component","--card-fill-entry","Plane parked just before the entry edge","—","100%","100%","new"),
 ("Component","--card-fill-exit","Plane parked just past the exit edge","—","-100%","-100%","new"),
 ("Component","--card-fill-travel","Distance from entry to covering (= covering − entry)","—","-100%","-100%","new"),
 ("Component","--card-fill-duration","Fill pass-through length","—","400ms","400ms","new"),
 ("Component","--member-name-gap","Team card: space between the name box and the card edge","0","0.5rem","0.5rem","new"),
 ("Component","--member-name-pad","Team card: name box side padding (also the hover pill's)","0.5rem","0.75rem","0.75rem","new"),
 ("Component","--location-scrim","Location card photo scrim (under the address)","—","linear-gradient(180deg, rgb(18 48 46 / 0) 35%, rgb(18 48 46 / .78) 100%)","linear-gradient(180deg, rgb(30 37 48 / 0) 35%, rgb(30 37 48 / .78) 100%)","new"),
 ("Component","--table-head-bg","Price table header ground","#018E87","var(--clr-surface)","var(--clr-surface)","new"),
 ("Component","--table-row-hover","Price table row hover","—","var(--clr-tint)","var(--clr-tint)","new"),
 ("Component","--member-reveal","Team card photo reveal duration","0.25s","350ms","350ms","new"),
 ("Component","--member-ring","Team card photo ring on hover","—","var(--clr-base)","var(--clr-base)","new"),
 ("Component","--member-pill-bg","Team card name pill on hover (over the photo)","rgb(0 0 0 / .5)","rgb(0 0 0 / .5)","rgb(0 0 0 / .5)","new"),
 ("Component","--member-pill-backdrop","Team card name pill backdrop filter","blur(5px)","blur(5px)","blur(5px)","new"),
 ("Component","--filter-hover-scale","Filter button pop-out on hover (cards use --card-hover-scale)","—","none","none","new"),
 ("Component","--filter-pad-block","Filter button padding, top = bottom","—","1rem","1rem","new"),
 ("Component","--filter-pad-inline","Filter button side padding","—","1.25rem","1.25rem","new"),
 ("Component","--filter-bar-offset","Category bar distance from the filter button's bottom edge","—",".375rem",".375rem","new"),
 ("Component","--aud-display","Audience label + bar on service cards","none","none","none","new"),
 ("Component","--card-pad-bottom","Service card bottom padding (room for the audience label)","2rem","2rem","2rem","new"),
 ("Component","--card-icon-offset","Space above the service icon","2rem","2rem","2rem","new"),
 ("Component","--aud-bottom","Audience label distance from the card's bottom edge","—","1rem","1rem","new"),
 ("Component","--aud-size","Audience label size","—","0.75rem","0.75rem","new"),
 ("Component","--aud-bar-w","Audience bar width","—","3.5rem","3.5rem","new"),
 ("Component","--aud-key-w","Colour key width inside the pill-bar preset","—","1.5rem","1.5rem","new"),
 ("Component","--aud-key-h","Colour key height inside the pill-bar preset","—","6px","6px","new"),
 ("Component","--aud-pill-neutral","Pill-bar preset ground","—","var(--clr-surface)","var(--clr-surface)","new"),
 ("Component","--aud-bar-h","Audience bar height","—","4px","4px","new"),
 ("Component","--card-icon-blend","Icon blend at rest","normal","normal","normal","new"),
 ("Component","--card-hover-icon-blend","Icon blend on hover (multiply drops the white icon ground)","multiply","normal","normal","new"),
]

# ---------- Direction C · Blend = Refine + Fresh typography + teal's complementary coral
BLEND = {
 "--clr-accent":"#E8836B",
 "--clr-accent-soft":"#F6B39F",
 "--clr-accent-strong":"#B34A36",
 "--clr-tint":"#FBEDE6",
 "--clr-on-tint":"#0B5E59",
 "--clr-footer-link":"#F6B39F",
 "--clr-focus":"#B34A36",
 "--clr-focus-on-dark":"#F6B39F",
 "--btn-emph-bg":"var(--clr-accent)",
 "--btn-emph-fg":"#12302E",
 "--btn-emph-hover-bg":"var(--clr-accent-soft)",
 "--btn-emph-hover-fg":"#12302E",
 "--cta-emph-bg":"var(--clr-accent)",
 "--cta-emph-fg":"#12302E",
 "--cta-emph-border":"var(--clr-accent)",
 "--cta-emph-hover-bg":"var(--clr-accent)",
 "--cta-hover-bg":"transparent",
 "--cta-emph-fill":"var(--clr-accent-soft)",
 "--action-panel-bg":"var(--clr-accent)",
 "--action-panel-fg":"#12302E",
 "--card-hover-border":"var(--clr-accent)",
 # navigation: detached frosted anthracite drawer on the left
 "--nav-left":"var(--nav-gap)",
 "--nav-right":"auto",
 "--nav-gap":"clamp(1.25rem, 3vw, 1.5rem)",
 "--nav-z":"850",
 "--nav-overlay-z":"840",
 "--nav-width":"400px",
 "--nav-pad":".5rem",
 "--nav-radius":"1.25rem",
 "--nav-bg":"rgb(38 42 46 / .72)",
 "--nav-backdrop":"blur(18px) saturate(140%)",
 "--nav-border":"rgb(255 255 255 / .12)",
 "--nav-shadow":"0 24px 60px rgb(0 0 0 / .28)",
 "--nav-hidden-x":"calc(-100% - 2 * var(--nav-gap))",
 "--nav-duration":"350ms",
 "--nav-overlay-bg":"rgb(20 24 27 / .28)",
 "--nav-weight":"600",
 "--nav-tracking":".06em",
 "--nav-size":".9375rem",
 "--nav-sub-case":"none",
 "--nav-sub-weight":"500",
 "--nav-item-radius":".75rem",
 "--nav-item-hover":"rgb(255 255 255 / .08)",
 "--mnav-gap":"var(--nav-gap)",
 "--mnav-radius":"var(--nav-radius)",
 "--mnav-bg":"var(--nav-bg)",
 "--mnav-backdrop":"var(--nav-backdrop)",
 "--mnav-border":"var(--nav-border)",
 "--mnav-shadow":"var(--nav-shadow)",
 "--mnav-pad-block":".375rem",
 "--mnav-pad-inline":".375rem",
 "--nav-avatar-display":"block",
 # sub-page header: brand aurora + eyebrow title (the page H1 is the one big title)
 "--color-bg1":"#0B5E59",
 "--color-bg2":"#12302E",
 "--color1":"1, 142, 135",
 "--color2":"232, 131, 107",
 "--color3":"121, 168, 87",
 "--color4":"246, 179, 159",
 "--color5":"104, 161, 202",
 "--blending":"screen",
 "--ph-height":"clamp(10rem, 24vh, 15rem)",
 "--ph-title-size":".8125rem",
 "--ph-title-offset":"1.5rem",
 "--ph-title-tracking":".18em",
 "--ph-title-weight":"600",
 "--aud-display":"block",
 "--card-pad-bottom":"3.75rem",
 "--card-icon-offset":".75rem",
 "--nav-avatar-pad":".375rem",
 "--nav-avatar-row-radius":"999px",
 "--card-hover-bg":"var(--clr-surface-raised)",
 # Rise (default): a solid coral plane rises through the card and exits at the top
 "--card-fill-final":"var(--clr-accent)",
 "--card-icon-blend":"multiply",
 "--card-hover-fg":"#12302E",
 "--card-hover-scale":"1.1",
 "--filter-hover-scale":"1.05",
 "--member-ring":"var(--clr-accent)",
 "--member-pill-bg":"var(--nav-bg)",
 "--member-pill-backdrop":"var(--nav-backdrop)",
 "--card-hover-transform":"none",
 "--card-hover-icon-blend":"multiply",
 # typography: Fraunces headings (from Fresh), Newsreader paragraphs,
 # Instrument Sans for navigation, buttons and other UI
 "--font-regular":"\"Instrument Sans\", system-ui, sans-serif",
 "--font-text":"Newsreader, Georgia, serif",
 "--text-size-adjust":"0.5",
 "--font-display":"Fraunces, Georgia, serif",
 "--display-variation":"\"SOFT\" 100, \"WONK\" 0",
 "--font-weight-h1":"500","--font-weight-h2":"400","--font-weight-card":"500",
 "--font-size-h2":"clamp(1.875rem, 1.6rem + 1.2vi, 2.625rem)",
 "--font-size-h1":"clamp(2.375rem, 1.9rem + 2vi, 3.5rem)",
 "--line-height-body":"1.6","--line-height-heading":"1.15","--tracking-heading":"-0.015em",
 "--measure":"66ch",
}

# ---------- Tertiary palette (RYB tertiaries around teal = blue-green, coral = red-orange)
_TER = [
 ("ochre","yellow-orange · dzieci / Psyche KIDS","#FCF3E3","#CE8F22","#885E16"),
 ("sage","yellow-green · on-line, wellbeing","#EFF6E9","#79A857","#4D6C37"),
 ("berry","red-violet · dorośli, pary","#F8E8F0","#CD84AB","#9C4071"),
 ("sky","blue · młodzież, diagnostyka (QEEG, ADOS-2)","#E7F1F9","#68A1CA","#31668C"),
]
for _n,_role,_soft,_base,_strong in _TER:
    for _step,_v,_use in (("soft",_soft,"tint ground for chips, badges, bands"),("base",_base,"fills with dark ink text, icons, rules"),("strong",_strong,"text & outlines on white / soft")):
        T.append(("Tertiary",f"--clr-{_n}-{_step}",f"{_role} — {_use}","—",_v,_v,"new"))
T += [
 ("Tertiary","--clr-cat-kids","Team filter: kids (team.css)","orange","var(--clr-ochre-base)","var(--clr-ochre-base)","new"),
 ("Tertiary","--clr-cat-youth","Team filter: youth","blue","var(--clr-sky-base)","var(--clr-sky-base)","new"),
 ("Tertiary","--clr-cat-adult","Team filter: adults","red","var(--clr-berry-base)","var(--clr-berry-base)","new"),
 ("Tertiary","--clr-cat-kids-tint","Kids pill ground","—","color-mix(in oklab, var(--clr-cat-kids) 40%, white)","color-mix(in oklab, var(--clr-cat-kids) 40%, white)","new"),
 ("Tertiary","--clr-cat-youth-tint","Youth pill ground","—","color-mix(in oklab, var(--clr-cat-youth) 40%, white)","color-mix(in oklab, var(--clr-cat-youth) 40%, white)","new"),
 ("Tertiary","--clr-cat-adult-tint","Adults pill ground","—","color-mix(in oklab, var(--clr-cat-adult) 40%, white)","color-mix(in oklab, var(--clr-cat-adult) 40%, white)","new"),
 ("Tertiary","--clr-cat-online-tint","On-line pill segment","—","color-mix(in oklab, var(--clr-cat-online) 40%, white)","color-mix(in oklab, var(--clr-cat-online) 40%, white)","new"),
 ("Tertiary","--clr-cat-online","Team filter: on-line","green","var(--clr-sage-base)","var(--clr-sage-base)","new"),
]
TERTIARY = _TER

# keep rows grouped by section after the additions above
_order = []
for _t in T:
    if _t[0] not in _order: _order.append(_t[0])
T.sort(key=lambda t: _order.index(t[0]))

# Alternative fill preset for C: diagonal sweep from the bottom-right corner.
# Emitted as :root[data-card-fill="sweep"] so it can be compared in the lab; to ship it,
# copy these values into :root instead.
BLEND_SWEEP = {
 # A 3x-wide square plane carrying one diagonal coral stripe (middle third, 135deg),
 # so both the leading and trailing edges are diagonal. Travels bottom-right → top-left.
 # Geometry (units of the plane): entry 0 (stripe touches the card's bottom-right corner),
 # covering −1/3 (stripe exactly spans the card), exit −2/3 (stripe cleared the top-left).
 "--card-fill-mask":"linear-gradient(135deg, transparent 33.333%, #000 33.333% 66.667%, transparent 66.667%)",
 "--card-fill-dx":"1",
 "--card-fill-w":"300%",
 "--card-fill-h":"auto",
 "--card-fill-entry":"0%",
 "--card-fill-exit":"-66.667%",
 "--card-fill-travel":"-33.333%",
 "--card-fill-duration":"500ms",
}

